name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate 3D profile
        uses: yoshi389111/github-profile-3d-contrib@0.8.0
        env:
          GITHUB_NAME: GuilhermeMPCosta
          OUTPUT_PATH: "./profile-3d-contrib/profile-night-rainbow.svg"
          THEME: "night-rainbow"

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add profile-3d-contrib/profile-night-rainbow.svg
          git commit -m "update 3D profile graph" || echo "No changes to commit"
          git push
