name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * 0" # Executa todo domingo à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate 3D profile
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@main
        with:
          username: GuilhermeMPCosta

      - name: Commit & Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Generate 3D contribution graph" || echo "No changes to commit"
          git push
